import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { CartProvider } from "@/components/context/cartContext";
import CartPreview from "@/components/cartPreview";

const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  weight: ["600"],
  variable: "--font-source-code-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sourceCodePro.variable} antialiased min-h-screen flex flex-col`}
      ><CartProvider>
        <Navbar />
        <main className="flex-1">{children}</main>
        <Footer />
        <CartPreview />
        
        </CartProvider>
      </body>
    </html>
  );
}
